"""campos libres inicial

Revision ID: campos_libres_0001
Revises:
Create Date: 2026-08-16 09:50:17.508479

Fase 21: `definicion` (qué campos existen por cuenta y tipo de entidad, sin
RLS — igual que `core.entrada_diccionario`) y `valor` (el valor de cada
campo en un registro concreto, CON RLS de organización como cualquier tabla
de negocio). Ver el docstring de `campos_libres/models.py` para por qué
`valor.entidad_id` no lleva FK real a la tabla de negocio correspondiente.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.rls import activar_rls, conceder_privilegios_app, desactivar_rls, revocar_privilegios_app

revision: str = 'campos_libres_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = ('campos_libres',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS campos_libres")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definicion',
    sa.Column('cuenta_id', sa.UUID(), nullable=False),
    sa.Column('entidad', sa.Enum('tercero', 'producto', 'obra', 'presupuesto', 'capitulo', 'partida', 'linea_medicion', 'asignacion', 'parte_trabajo', name='entidad_campo_libre', native_enum=False, length=32), nullable=False),
    sa.Column('clave', sa.String(length=64), nullable=False),
    sa.Column('etiqueta', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('texto', 'numero', 'fecha', 'booleano', 'select', name='tipo_campo_libre', native_enum=False, length=32), nullable=False),
    sa.Column('opciones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['core.cuenta.id'], name=op.f('fk_definicion_cuenta_id_cuenta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_definicion')),
    sa.UniqueConstraint('cuenta_id', 'entidad', 'clave', name='campo_libre_definicion_unique'),
    schema='campos_libres'
    )
    op.create_table('valor',
    sa.Column('entidad', sa.Enum('tercero', 'producto', 'obra', 'presupuesto', 'capitulo', 'partida', 'linea_medicion', 'asignacion', 'parte_trabajo', name='entidad_campo_libre', native_enum=False, length=32), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('definicion_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definicion_id'], ['campos_libres.definicion.id'], name=op.f('fk_valor_definicion_id_definicion'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_valor_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valor')),
    sa.UniqueConstraint('organization_id', 'entidad', 'entidad_id', 'definicion_id', name='campo_libre_valor_unique'),
    schema='campos_libres'
    )
    op.create_index(op.f('ix_campos_libres_valor_entidad_id'), 'valor', ['entidad_id'], unique=False, schema='campos_libres')
    op.create_index(op.f('ix_campos_libres_valor_organization_id'), 'valor', ['organization_id'], unique=False, schema='campos_libres')
    # ### end Alembic commands ###

    activar_rls("campos_libres", "valor")

    # Schema nuevo: sin esto el rol de mínimo privilegio no tiene ni USAGE
    # sobre él (lección de la Fase 7).
    conceder_privilegios_app("campos_libres")


def downgrade() -> None:
    revocar_privilegios_app("campos_libres")
    desactivar_rls("campos_libres", "valor")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campos_libres_valor_organization_id'), table_name='valor', schema='campos_libres')
    op.drop_index(op.f('ix_campos_libres_valor_entidad_id'), table_name='valor', schema='campos_libres')
    op.drop_table('valor', schema='campos_libres')
    op.drop_table('definicion', schema='campos_libres')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS campos_libres CASCADE")
