"""forma juridica y tratamiento

Revision ID: 5eef0f540e95
Revises: terceros_0002
Create Date: 2026-08-16 09:33:49.448927

Fase 20: dos referencias nuevas al diccionario de la cuenta (ver
`core/diccionario_models.py`) — `Tercero.forma_juridica` (S.L., S.A.,
Autónomo...) y `Contacto.tratamiento` (Sr., Sra., Don, Doña...). Libres, sin
enum de código detrás: a diferencia de `forma_pago`, no hay ninguna otra
tabla que restrinja qué valores son válidos.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5eef0f540e95'
down_revision: str | None = 'terceros_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacto', sa.Column('tratamiento', sa.String(length=32), nullable=True), schema='terceros')
    op.add_column('tercero', sa.Column('forma_juridica', sa.String(length=64), nullable=True), schema='terceros')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tercero', 'forma_juridica', schema='terceros')
    op.drop_column('contacto', 'tratamiento', schema='terceros')
    # ### end Alembic commands ###
