"""versiones y plantillas

Revision ID: 348ae1ac40fa
Revises: 6147a90e5552
Create Date: 2026-08-08 17:41:20.063841
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '348ae1ac40fa'
down_revision: str | None = '6147a90e5552'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('presupuesto', sa.Column('raiz_id', sa.UUID(), nullable=True), schema='presupuestos')
    # server_default en las columnas NOT NULL: la tabla ya tiene filas y sin él
    # el ALTER falla. Se retira después para que el valor lo ponga la
    # aplicación y no quede un default silencioso en el esquema.
    op.add_column(
        'presupuesto',
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        schema='presupuestos',
    )
    op.add_column(
        'presupuesto',
        sa.Column('es_plantilla', sa.Boolean(), nullable=False, server_default=sa.false()),
        schema='presupuestos',
    )
    op.add_column('presupuesto', sa.Column('tipo_obra', sa.String(length=120), nullable=True), schema='presupuestos')
    op.alter_column('presupuesto', 'version', server_default=None, schema='presupuestos')
    op.alter_column('presupuesto', 'es_plantilla', server_default=None, schema='presupuestos')
    op.create_index(op.f('ix_presupuestos_presupuesto_raiz_id'), 'presupuesto', ['raiz_id'], unique=False, schema='presupuestos')
    op.create_index(op.f('ix_presupuestos_presupuesto_tipo_obra'), 'presupuesto', ['tipo_obra'], unique=False, schema='presupuestos')
    op.create_foreign_key(op.f('fk_presupuesto_raiz_id_presupuesto'), 'presupuesto', 'presupuesto', ['raiz_id'], ['id'], source_schema='presupuestos', referent_schema='presupuestos', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_presupuesto_raiz_id_presupuesto'), 'presupuesto', schema='presupuestos', type_='foreignkey')
    op.drop_index(op.f('ix_presupuestos_presupuesto_tipo_obra'), table_name='presupuesto', schema='presupuestos')
    op.drop_index(op.f('ix_presupuestos_presupuesto_raiz_id'), table_name='presupuesto', schema='presupuestos')
    op.drop_column('presupuesto', 'tipo_obra', schema='presupuestos')
    op.drop_column('presupuesto', 'es_plantilla', schema='presupuestos')
    op.drop_column('presupuesto', 'version', schema='presupuestos')
    op.drop_column('presupuesto', 'raiz_id', schema='presupuestos')
    # ### end Alembic commands ###
