"""presupuesto capitulos partidas mediciones

Revision ID: 6147a90e5552
Revises: presupuestos_0001
Create Date: 2026-08-08 17:21:22.483035
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6147a90e5552'
down_revision: str | None = 'presupuestos_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuesto',
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('emplazamiento', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('validez_dias', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'emitido', 'aprobado', 'rechazado', 'cancelado', name='estado_presupuesto', native_enum=False, length=32), nullable=False),
    sa.Column('gastos_generales', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('beneficio_industrial', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tipo_iva', sa.Enum('general', 'reducido', 'superreducido', 'exento', name='tipo_iva', native_enum=False, length=32), nullable=False),
    sa.Column('inversion_sujeto_pasivo', sa.Boolean(), nullable=False),
    sa.Column('precios_bloqueados', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('origen_dato', sa.Enum('manual', 'fiebdc3', 'ia', 'importado', name='origen_dato', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['terceros.tercero.id'], name=op.f('fk_presupuesto_cliente_id_tercero'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_presupuesto_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presupuesto')),
    sa.UniqueConstraint('organization_id', 'codigo', name='presupuesto_codigo_unique'),
    schema='presupuestos'
    )
    op.create_index(op.f('ix_presupuestos_presupuesto_cliente_id'), 'presupuesto', ['cliente_id'], unique=False, schema='presupuestos')
    op.create_index('ix_presupuestos_presupuesto_estado', 'presupuesto', ['organization_id', 'estado'], unique=False, schema='presupuestos')
    op.create_index(op.f('ix_presupuestos_presupuesto_organization_id'), 'presupuesto', ['organization_id'], unique=False, schema='presupuestos')
    op.create_table('capitulo',
    sa.Column('presupuesto_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('resumen', sa.String(length=250), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_capitulo_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['presupuestos.capitulo.id'], name=op.f('fk_capitulo_parent_id_capitulo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.presupuesto.id'], name=op.f('fk_capitulo_presupuesto_id_presupuesto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capitulo')),
    schema='presupuestos'
    )
    op.create_index(op.f('ix_presupuestos_capitulo_organization_id'), 'capitulo', ['organization_id'], unique=False, schema='presupuestos')
    op.create_index('ix_presupuestos_capitulo_parent', 'capitulo', ['parent_id'], unique=False, schema='presupuestos')
    op.create_index('ix_presupuestos_capitulo_presupuesto', 'capitulo', ['presupuesto_id'], unique=False, schema='presupuestos')
    op.create_table('partida',
    sa.Column('presupuesto_id', sa.UUID(), nullable=False),
    sa.Column('capitulo_id', sa.UUID(), nullable=False),
    sa.Column('concepto_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('resumen', sa.String(length=250), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('unidad', sa.String(length=10), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('medicion', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('importe', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['presupuestos.capitulo.id'], name=op.f('fk_partida_capitulo_id_capitulo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concepto_id'], ['presupuestos.concepto.id'], name=op.f('fk_partida_concepto_id_concepto'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_partida_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.presupuesto.id'], name=op.f('fk_partida_presupuesto_id_presupuesto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partida')),
    schema='presupuestos'
    )
    op.create_index('ix_presupuestos_partida_capitulo', 'partida', ['capitulo_id'], unique=False, schema='presupuestos')
    op.create_index('ix_presupuestos_partida_concepto', 'partida', ['concepto_id'], unique=False, schema='presupuestos')
    op.create_index(op.f('ix_presupuestos_partida_organization_id'), 'partida', ['organization_id'], unique=False, schema='presupuestos')
    op.create_index('ix_presupuestos_partida_presupuesto', 'partida', ['presupuesto_id'], unique=False, schema='presupuestos')
    op.create_table('linea_medicion',
    sa.Column('partida_id', sa.UUID(), nullable=False),
    sa.Column('comentario', sa.String(length=250), nullable=True),
    sa.Column('uds', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('anchura', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('altura', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('parcial', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_linea_medicion_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partida_id'], ['presupuestos.partida.id'], name=op.f('fk_linea_medicion_partida_id_partida'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linea_medicion')),
    schema='presupuestos'
    )
    op.create_index(op.f('ix_presupuestos_linea_medicion_organization_id'), 'linea_medicion', ['organization_id'], unique=False, schema='presupuestos')
    op.create_index('ix_presupuestos_linea_medicion_partida', 'linea_medicion', ['partida_id'], unique=False, schema='presupuestos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_presupuestos_linea_medicion_partida', table_name='linea_medicion', schema='presupuestos')
    op.drop_index(op.f('ix_presupuestos_linea_medicion_organization_id'), table_name='linea_medicion', schema='presupuestos')
    op.drop_table('linea_medicion', schema='presupuestos')
    op.drop_index('ix_presupuestos_partida_presupuesto', table_name='partida', schema='presupuestos')
    op.drop_index(op.f('ix_presupuestos_partida_organization_id'), table_name='partida', schema='presupuestos')
    op.drop_index('ix_presupuestos_partida_concepto', table_name='partida', schema='presupuestos')
    op.drop_index('ix_presupuestos_partida_capitulo', table_name='partida', schema='presupuestos')
    op.drop_table('partida', schema='presupuestos')
    op.drop_index('ix_presupuestos_capitulo_presupuesto', table_name='capitulo', schema='presupuestos')
    op.drop_index('ix_presupuestos_capitulo_parent', table_name='capitulo', schema='presupuestos')
    op.drop_index(op.f('ix_presupuestos_capitulo_organization_id'), table_name='capitulo', schema='presupuestos')
    op.drop_table('capitulo', schema='presupuestos')
    op.drop_index(op.f('ix_presupuestos_presupuesto_organization_id'), table_name='presupuesto', schema='presupuestos')
    op.drop_index('ix_presupuestos_presupuesto_estado', table_name='presupuesto', schema='presupuestos')
    op.drop_index(op.f('ix_presupuestos_presupuesto_cliente_id'), table_name='presupuesto', schema='presupuestos')
    op.drop_table('presupuesto', schema='presupuestos')
    # ### end Alembic commands ###
