"""patrones de numeracion de documentos

Revision ID: cc3da38b179b
Revises: 63821d58ff8a
Create Date: 2026-08-15 17:42:47.866973

Fase 16: patrón de numeración configurable por cuenta para el `codigo`
interno de Presupuesto/Albarán/Factura (nunca `Factura.serie`/`numero`, que
siguen la numeración fiscal de la Fase 8 — ver `numeracion_models.py`).

Backfill: sin esto, el primer documento nuevo de cada organización tras
esta migración volvería a generar "PRE00001"/"ALB00001"/"FAC00001" —
duplicado del ya existente. Se siembra `contador_documento` con el máximo
ya usado por organización, parseado del propio `codigo` con la misma
expresión regular que usaba el código viejo antes de esta fase.
"""
import re
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cc3da38b179b'
down_revision: str | None = '63821d58ff8a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = ("compras", "facturacion")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contador_documento',
    sa.Column('ambito_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('presupuesto', 'albaran', 'factura', name='tipo_documento_numeracion', native_enum=False, length=32), nullable=False),
    sa.Column('ultimo', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contador_documento')),
    sa.UniqueConstraint('ambito_id', 'tipo_documento', name='contador_documento_unique'),
    schema='core'
    )
    op.create_table('patron_numeracion',
    sa.Column('cuenta_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('presupuesto', 'albaran', 'factura', name='tipo_documento_numeracion', native_enum=False, length=32), nullable=False),
    sa.Column('patron', sa.String(length=80), nullable=False),
    sa.Column('secuencia_compartida', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['core.cuenta.id'], name=op.f('fk_patron_numeracion_cuenta_id_cuenta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patron_numeracion')),
    sa.UniqueConstraint('cuenta_id', 'tipo_documento', name='patron_numeracion_unique'),
    schema='core'
    )
    # ### end Alembic commands ###

    conn = op.get_bind()
    _backfill_contador(conn, tabla='presupuestos.presupuesto', prefijo='PRE', tipo='presupuesto')
    _backfill_contador(conn, tabla='compras.albaran', prefijo='ALB', tipo='albaran')
    _backfill_contador(conn, tabla='facturacion.factura', prefijo='FAC', tipo='factura')


def _backfill_contador(conn, *, tabla: str, prefijo: str, tipo: str) -> None:
    filas = conn.execute(sa.text(f'SELECT organization_id, codigo FROM {tabla}')).fetchall()
    patron = re.compile(rf'^{prefijo}(\d+)$')
    maximos: dict[uuid.UUID, int] = {}
    for organization_id, codigo in filas:
        encaje = patron.match(codigo)
        if encaje:
            maximos[organization_id] = max(maximos.get(organization_id, 0), int(encaje.group(1)))

    for organization_id, maximo in maximos.items():
        conn.execute(
            sa.text(
                'INSERT INTO core.contador_documento (id, ambito_id, tipo_documento, ultimo) '
                'VALUES (:id, :ambito_id, :tipo, :ultimo)'
            ),
            {'id': uuid.uuid4(), 'ambito_id': organization_id, 'tipo': tipo, 'ultimo': maximo},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patron_numeracion', schema='core')
    op.drop_table('contador_documento', schema='core')
    # ### end Alembic commands ###
