"""grupos y permisos por modulo

Revision ID: b7561edc2c04
Revises: feb570badbbb
Create Date: 2026-08-10 08:01:54.848126
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.rls import activar_rls, desactivar_rls

revision: str = 'b7561edc2c04'
down_revision: str | None = 'feb570badbbb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_grupo_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo')),
    sa.UniqueConstraint('organization_id', 'nombre', name='grupo_nombre_unique'),
    schema='core'
    )
    op.create_index(op.f('ix_core_grupo_organization_id'), 'grupo', ['organization_id'], unique=False, schema='core')
    op.create_table('grupo_permiso',
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('ver', sa.Enum('ninguno', 'propios', 'todos', name='alcance_ver', native_enum=False, length=32), nullable=False),
    sa.Column('editar', sa.Enum('ninguno', 'propios', 'todos', name='alcance_editar', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['core.grupo.id'], name=op.f('fk_grupo_permiso_grupo_id_grupo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_grupo_permiso_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo_permiso')),
    sa.UniqueConstraint('grupo_id', 'module_code', name='grupo_permiso_unique'),
    schema='core'
    )
    op.create_index(op.f('ix_core_grupo_permiso_organization_id'), 'grupo_permiso', ['organization_id'], unique=False, schema='core')
    op.create_table('grupo_usuario',
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_subject', sa.String(length=120), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['core.grupo.id'], name=op.f('fk_grupo_usuario_grupo_id_grupo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_grupo_usuario_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo_usuario')),
    sa.UniqueConstraint('grupo_id', 'usuario_subject', name='grupo_usuario_unique'),
    schema='core'
    )
    op.create_index(op.f('ix_core_grupo_usuario_organization_id'), 'grupo_usuario', ['organization_id'], unique=False, schema='core')
    op.create_index('ix_core_grupo_usuario_subject', 'grupo_usuario', ['organization_id', 'usuario_subject'], unique=False, schema='core')
    # ### end Alembic commands ###

    # A diferencia de Tarifa/Descuento (solo superadmin), los grupos también
    # los gestiona el propio tenant desde una pantalla normal — igual que
    # `organization_module`, por eso sí llevan RLS. El schema `core` ya tiene
    # los privilegios del rol de mínimo privilegio concedidos desde `core_0003`
    # (ALTER DEFAULT PRIVILEGES), así que no hace falta repetir el GRANT aquí.
    for tabla in ("grupo", "grupo_permiso", "grupo_usuario"):
        activar_rls("core", tabla)


def downgrade() -> None:
    for tabla in ("grupo_usuario", "grupo_permiso", "grupo"):
        desactivar_rls("core", tabla)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_core_grupo_usuario_subject', table_name='grupo_usuario', schema='core')
    op.drop_index(op.f('ix_core_grupo_usuario_organization_id'), table_name='grupo_usuario', schema='core')
    op.drop_table('grupo_usuario', schema='core')
    op.drop_index(op.f('ix_core_grupo_permiso_organization_id'), table_name='grupo_permiso', schema='core')
    op.drop_table('grupo_permiso', schema='core')
    op.drop_index(op.f('ix_core_grupo_organization_id'), table_name='grupo', schema='core')
    op.drop_table('grupo', schema='core')
    # ### end Alembic commands ###
