"""iva recargo y retencion en el diccionario

Revision ID: f8a08fb12cbf
Revises: 5eef0f540e95b
Create Date: 2026-08-16 10:25:00.488748

Fase 23: columna `valor` (el % que representa la entrada, cuando aplica) y
tres categorías nuevas — `iva`/`recargo_equivalencia` son solo de referencia
(el cálculo fiscal real sigue en `TipoIVA`/`TIPO_IVA_PORCENTAJE`, ver
`diccionario_models.py`), `retencion` sí es una sugerencia real para el
campo libre `Tercero.irpf_retencion`.
"""
import uuid
from collections.abc import Sequence
from decimal import Decimal

import sqlalchemy as sa
from alembic import op

revision: str = 'f8a08fb12cbf'
down_revision: str | None = '5eef0f540e95b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

IVA: list[tuple[str, str, str]] = [
    ('general', 'General', '21'),
    ('reducido', 'Reducido', '10'),
    ('superreducido', 'Superreducido', '4'),
    ('exento', 'Exento', '0'),
]

RECARGO_EQUIVALENCIA: list[tuple[str, str, str]] = [
    ('general', 'Tipo general', '5.2'),
    ('reducido', 'Tipo reducido', '1.4'),
    ('superreducido', 'Tipo superreducido', '0.5'),
]

RETENCION: list[tuple[str, str, str]] = [
    ('general', 'General (profesionales)', '15'),
    ('nuevos_autonomos', 'Nuevos autónomos (2 primeros años)', '7'),
    ('modulos', 'Módulos', '1'),
    ('capital_mobiliario', 'Capital mobiliario', '19'),
    ('alquiler', 'Alquiler de inmuebles', '19'),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrada_diccionario', sa.Column('valor', sa.Numeric(precision=7, scale=3), nullable=True), schema='core')
    # ### end Alembic commands ###

    conn = op.get_bind()
    cuenta_ids = [fila[0] for fila in conn.execute(sa.text('SELECT id FROM core.cuenta')).fetchall()]
    for cuenta_id in cuenta_ids:
        _sembrar(conn, cuenta_id, tipo='iva', entradas=IVA)
        _sembrar(conn, cuenta_id, tipo='recargo_equivalencia', entradas=RECARGO_EQUIVALENCIA)
        _sembrar(conn, cuenta_id, tipo='retencion', entradas=RETENCION)


def _sembrar(conn, cuenta_id: uuid.UUID, *, tipo: str, entradas: list[tuple[str, str, str]]) -> None:
    for orden, (clave, etiqueta, valor) in enumerate(entradas):
        conn.execute(
            sa.text(
                'INSERT INTO core.entrada_diccionario '
                '(id, cuenta_id, tipo, clave, etiqueta, valor, activo, orden) '
                'VALUES (:id, :cuenta_id, :tipo, :clave, :etiqueta, :valor, true, :orden)'
            ),
            {
                'id': uuid.uuid4(),
                'cuenta_id': cuenta_id,
                'tipo': tipo,
                'clave': clave,
                'etiqueta': etiqueta,
                'valor': Decimal(valor),
                'orden': orden,
            },
        )


def downgrade() -> None:
    op.execute(
        "DELETE FROM core.entrada_diccionario WHERE tipo IN ('iva', 'recargo_equivalencia', 'retencion')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrada_diccionario', 'valor', schema='core')
    # ### end Alembic commands ###
