"""tarifas descuentos uso ia cobros y ajustes globales

Revision ID: c7eb41f58eec
Revises: core_0003
Create Date: 2026-08-09 17:24:19.056343
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c7eb41f58eec'
down_revision: str | None = 'core_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deepseek_api_key', sa.String(length=200), nullable=True),
    sa.Column('deepseek_model', sa.String(length=60), nullable=False),
    sa.Column('deepseek_base_url', sa.String(length=200), nullable=False),
    sa.Column('gemini_api_key', sa.String(length=200), nullable=True),
    sa.Column('gemini_model', sa.String(length=60), nullable=False),
    sa.Column('gemini_base_url', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracion_ia')),
    schema='core'
    )
    op.create_table('configuracion_pasarela_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=200), nullable=True),
    sa.Column('vendor_id', sa.String(length=60), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracion_pasarela_pago')),
    schema='core'
    )
    op.create_table('configuracion_smtp_plataforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('puerto', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('remitente', sa.String(length=200), nullable=True),
    sa.Column('usa_tls', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracion_smtp_plataforma')),
    schema='core'
    )
    op.create_table('tarifa',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('precio_1000_tokens_deepseek', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('precio_1000_tokens_gemini', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarifa')),
    sa.UniqueConstraint('nombre', name='tarifa_nombre_unique'),
    schema='core'
    )
    op.create_table('tarifa_modulo',
    sa.Column('tarifa_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tarifa_id'], ['core.tarifa.id'], name=op.f('fk_tarifa_modulo_tarifa_id_tarifa'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarifa_modulo')),
    sa.UniqueConstraint('tarifa_id', 'module_code', name='tarifa_modulo_unique'),
    schema='core'
    )
    op.create_table('cobro_saas',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('concepto', sa.String(length=250), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('referencia_externa', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_cobro_saas_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cobro_saas')),
    schema='core'
    )
    op.create_index('ix_core_cobro_saas_organization', 'cobro_saas', ['organization_id'], unique=False, schema='core')
    op.create_table('configuracion_smtp_organizacion',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('puerto', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('remitente', sa.String(length=200), nullable=True),
    sa.Column('usa_tls', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_configuracion_smtp_organizacion_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_configuracion_smtp_organizacion')),
    schema='core'
    )
    op.create_table('descuento',
    sa.Column('tarifa_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('porcentaje', 'importe_fijo', name='tipo_descuento', native_enum=False, length=32), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_descuento_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarifa_id'], ['core.tarifa.id'], name=op.f('fk_descuento_tarifa_id_tarifa'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_descuento')),
    schema='core'
    )
    op.create_table('uso_ia',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('usuario_subject', sa.String(length=120), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=False),
    sa.Column('proveedor', sa.Enum('deepseek', 'gemini', name='proveedor_ia', native_enum=False, length=32), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_salida', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_uso_ia_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uso_ia')),
    schema='core'
    )
    op.create_index('ix_core_uso_ia_organization', 'uso_ia', ['organization_id'], unique=False, schema='core')
    op.create_index('ix_core_uso_ia_organization_created', 'uso_ia', ['organization_id', 'created_at'], unique=False, schema='core')
    op.add_column('organization', sa.Column('tarifa_id', sa.UUID(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_organization_tarifa_id_tarifa'), 'organization', 'tarifa', ['tarifa_id'], ['id'], source_schema='core', referent_schema='core', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_organization_tarifa_id_tarifa'), 'organization', schema='core', type_='foreignkey')
    op.drop_column('organization', 'tarifa_id', schema='core')
    op.drop_index('ix_core_uso_ia_organization_created', table_name='uso_ia', schema='core')
    op.drop_index('ix_core_uso_ia_organization', table_name='uso_ia', schema='core')
    op.drop_table('uso_ia', schema='core')
    op.drop_table('descuento', schema='core')
    op.drop_table('configuracion_smtp_organizacion', schema='core')
    op.drop_index('ix_core_cobro_saas_organization', table_name='cobro_saas', schema='core')
    op.drop_table('cobro_saas', schema='core')
    op.drop_table('tarifa_modulo', schema='core')
    op.drop_table('tarifa', schema='core')
    op.drop_table('configuracion_smtp_plataforma', schema='core')
    op.drop_table('configuracion_pasarela_pago', schema='core')
    op.drop_table('configuracion_ia', schema='core')
    # ### end Alembic commands ###
