"""monedas y tipo de cambio

Revision ID: db433ad465d8
Revises: f8a08fb12cbf
Create Date: 2026-08-16 10:30:12.328564

Fase 23: tabla de monedas a nivel de plataforma (no de cuenta — el cambio de
hoy es el mismo para todos, ver docstring de `moneda_models.py`). Se siembra
sin tipo de cambio (`unidades_por_euro=NULL`, salvo EUR=1): el primer
refresco lo rellena, vía `moneda_service.actualizar_tasas_cambio` (botón
manual o automático al leerse si lleva más de 24h caducado).
"""
import uuid
from collections.abc import Sequence
from decimal import Decimal

import sqlalchemy as sa
from alembic import op

revision: str = 'db433ad465d8'
down_revision: str | None = 'f8a08fb12cbf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MONEDAS: list[tuple[str, str, str, str | None]] = [
    ('EUR', 'Euro', '€', '1'),
    ('USD', 'Dólar estadounidense', '$', None),
    ('GBP', 'Libra esterlina', '£', None),
    ('CHF', 'Franco suizo', 'CHF', None),
    ('JPY', 'Yen japonés', '¥', None),
    ('MXN', 'Peso mexicano', '$', None),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneda',
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('simbolo', sa.String(length=5), nullable=False),
    sa.Column('unidades_por_euro', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moneda')),
    sa.UniqueConstraint('codigo', name=op.f('uq_moneda_codigo')),
    schema='core'
    )
    # ### end Alembic commands ###

    conn = op.get_bind()
    for codigo, nombre, simbolo, unidades_por_euro in MONEDAS:
        conn.execute(
            sa.text(
                'INSERT INTO core.moneda (id, codigo, nombre, simbolo, unidades_por_euro) '
                'VALUES (:id, :codigo, :nombre, :simbolo, :unidades_por_euro)'
            ),
            {
                'id': uuid.uuid4(),
                'codigo': codigo,
                'nombre': nombre,
                'simbolo': simbolo,
                'unidades_por_euro': Decimal(unidades_por_euro) if unidades_por_euro else None,
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneda', schema='core')
    # ### end Alembic commands ###
