"""overrides de traduccion por cuenta

Revision ID: bf130a64f9c2
Revises: 1457b7e50efd
Create Date: 2026-08-16 08:33:24.759397
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'bf130a64f9c2'
down_revision: str | None = '1457b7e50efd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traduccion_override',
    sa.Column('cuenta_id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=200), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['core.cuenta.id'], name=op.f('fk_traduccion_override_cuenta_id_cuenta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traduccion_override')),
    sa.UniqueConstraint('cuenta_id', 'clave', name='traduccion_override_unique'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traduccion_override', schema='core')
    # ### end Alembic commands ###
