"""catalogo reutilizable de descuentos

Revision ID: feb570badbbb
Revises: 9f859daaf6cb
Create Date: 2026-08-09 18:42:36.870963
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'feb570badbbb'
down_revision: str | None = '9f859daaf6cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacion_descuento',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('descuento_id', sa.UUID(), nullable=False),
    sa.Column('aplicado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anulado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['descuento_id'], ['core.descuento.id'], name=op.f('fk_organizacion_descuento_descuento_id_descuento'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['core.organization.id'], name=op.f('fk_organizacion_descuento_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizacion_descuento')),
    schema='core'
    )
    op.create_index('ix_core_organizacion_descuento_organization', 'organizacion_descuento', ['organization_id'], unique=False, schema='core')
    op.drop_constraint(op.f('fk_descuento_organization_id_organization'), 'descuento', schema='core', type_='foreignkey')
    op.drop_column('descuento', 'organization_id', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descuento', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_descuento_organization_id_organization'), 'descuento', 'organization', ['organization_id'], ['id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.drop_index('ix_core_organizacion_descuento_organization', table_name='organizacion_descuento', schema='core')
    op.drop_table('organizacion_descuento', schema='core')
    # ### end Alembic commands ###
